# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-02-10 05:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empdtls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=12)),
                ('lastname', models.CharField(max_length=12)),
                ('emp_id', models.CharField(max_length=9)),
                ('mail_id', models.EmailField(blank=True, max_length=23)),
                ('contact_no', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
    ]
