# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-05 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20170210_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empdtls',
            name='emp_id',
            field=models.AutoField(max_length=9, primary_key=True, serialize=False),
        ),
    ]
